"""Initial migration

Revision ID: 0770a60f7ad9
Revises: 
Create Date: 2025-05-29 21:12:51.560351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0770a60f7ad9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=True),
    sa.Column('last_searched', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city_search')
    # ### end Alembic commands ###
